version: '3.8'

services:
  prologue-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_NAME=Prologue
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local 